package upec.alzproject;
import upec.AssistancePlan;
import upec.Diagnosis;
import upec.NeuropsychologicalParameter;
import upec.Treatment;
import upec.PatientRecord;

rule"reinserting patient symptoms into the wm"
ruleflow-group"NeurolgoyService2"
salience 4
no-loop true
when
patient:upec.PatientRecord( syl:symptoms)
sy:upec.Symptom( )from syl
then
insertLogical(sy);
System.out.println("insert fact:"+ sy.getDescription());
end

rule"reinserting neuropsychological parameters into the wm"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
patient:upec.PatientRecord( neuroparameters:neuropsychologicalParameters)
neuroparameter: NeuropsychologicalParameter() from neuroparameters
then
insertLogical(neuroparameter);
System.out.println("insert fact: "+ neuroparameter.getName()+ "Value:"+ neuroparameter.getValue());
end





rule"Alzheimer stage 1"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
mmse:upec.NeuropsychologicalParameter( name=="MMSE score" && value>20)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alzheimer mild stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end

rule"Alzheimer stage 2"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
mmse:upec.NeuropsychologicalParameter( name=="MMSE score" && value>10 && value <20)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alzheimer moderate stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end


rule"Alzheimer stage 3"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
mmse:upec.NeuropsychologicalParameter(name=="MMSE score" && value <10)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alhzeimer severe stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end

