package upec.alzproject;
import upec.PatientRecord;
import upec.Symptom;
import upec.MedicalExamination;
import upec.NeuropsychologicalParameter;
import upec.Assignement;
import upec.Diagnosis;

rule "inserting patient clinical examinations into the wm"
ruleflow-group"NeurologyService1"
salience 4
no-loop true
when
patient:upec.PatientRecord( exams:medicalExaminations)
exam:upec.MedicalExamination( )from exams
then
insertLogical(exam);
System.out.println("insert fact: "+ exam.getName()+ "result:"+exam.getResult());
end

rule"inserting neuropsychological parameters into the wm"
ruleflow-group"NeurologyService1"
salience 4
no-loop true
when
patient:upec.PatientRecord( neuroparameters:neuropsychologicalParameters)
neuroparameter: NeuropsychologicalParameter() from neuroparameters
then
insertLogical(neuroparameter);
System.out.println("insert fact: "+ neuroparameter.getName()+ "Value:"+ neuroparameter.getValue());
end



rule"Alzheimer stage 1"
ruleflow-group"NeurologyService1"
salience 2
no-loop true
when
mmse:upec.NeuropsychologicalParameter( name=="MMSE score" && value>20)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alhzeimer mild stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end

rule"Alzheimer stage 2"
ruleflow-group"NeurologyService1"
salience 2
no-loop true
when
mmse:upec.NeuropsychologicalParameter( name=="MMSE score" && value>10 && value <20)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alhzeimer moderate stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end


rule"Alzheimer stage 3"
ruleflow-group"NeurologyService1"
salience 2
no-loop true
when
mmse:upec.NeuropsychologicalParameter(name=="MMSE score" && value <10)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alhzeimer severe stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end

rule"alzheimer treatment1"
ruleflow-group"NeurologyService1"
salience 4
no-loop true
when
diagnosis:upec.Diagnosis(value=="Alhzeimer mild stage")
treatment:upec.Treatment( )
then
treatment.setName("cholinesterase inhibitor");
end

rule"alzheimer treatment2"
ruleflow-group"NeurologyService1"
salience 4
no-loop true
when
diagnosis:upec.Diagnosis(value=="Alhzeimer moderate stage")
treatment:upec.Treatment( )
then
treatment.setName("Cholinesterase inhibitor or an anti-glutamate");
end

rule"alzheimer treatment3"
ruleflow-group"NeurologyService1"
salience 4
no-loop true
when
diagnosis:upec.Diagnosis(value=="Alhzeimer severe stage")
treatment:upec.Treatment( )
then
treatment.setName("Anti-glutamate");
end