package upec.alzproject;
import upec.AssistancePlan;
import upec.Diagnosis;
import upec.NeuropsychologicalParameter;
import upec.Treatment;
import upec.PatientRecord;

rule"reinserting patient symptoms into the wm"
ruleflow-group"NeurolgoyService2"
salience 4
no-loop true
when
patient:upec.PatientRecord( syl:symptoms)
sy:upec.Symptom( )from syl
then
insertLogical(sy);
System.out.println("insert fact:"+ sy.getDescription());
end

rule"reinserting neuropsychological parameters into the wm"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
patient:upec.PatientRecord( neuroparameters:neuropsychologicalParameters)
neuroparameter: NeuropsychologicalParameter() from neuroparameters
then
insertLogical(neuroparameter);
System.out.println("insert fact: "+ neuroparameter.getName()+ "Value:"+ neuroparameter.getValue());
end





rule"Alzheimer stage 1"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
mmse:upec.NeuropsychologicalParameter( name=="MMSE score" && value>20)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alzheimer mild stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end

rule"Alzheimer stage 2"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
mmse:upec.NeuropsychologicalParameter( name=="MMSE score" && value>10 && value <20)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alzheimer moderate stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end


rule"Alzheimer stage 3"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
mmse:upec.NeuropsychologicalParameter(name=="MMSE score" && value <10)
diagnosis:upec.Diagnosis( this!=null)
then
diagnosis.setValue("Alhzeimer severe stage");
System.out.println("Diagnosis: "+ diagnosis.getValue());
end

rule"alzheimer treatment1"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
diagnosis:upec.Diagnosis(value=="Alzheimer mild stage")
treatment:upec.Treatment( )
then
treatment.setName("cholinesterase inhibitor");
end

rule"alzheimer treatment2"
ruleflow-group"NeurologyService2"
salience 4
no-loop true
when
diagnosis:upec.Diagnosis(value=="Alzheimer moderate stage")
treatment:upec.Treatment( )
then
treatment.setName("Cholinesterase inhibitor or an anti-glutamate");
end

rule"alzheimer treatment3"
ruleflow-group"NeurologyService1"
salience 4
no-loop true
when
diagnosis:upec.Diagnosis(value=="Alzheimer severe stage")
treatment:upec.Treatment( )
then
treatment.setName("Anti-glutamate");
end


rule"assistance plan 1"
ruleflow-group"NeurologyService2"
salience 2
when
syp1:upec.Symptom(description=="Aphasia" )
plan1:upec.AssistancePlan(this!=null )
then
plan1.setDescription("Speech therapy");
end

rule"assistance plan 2"
ruleflow-group"NeurologyService2"
salience 4
when
syp1:upec.Symptom(description=="Cognitive impairment" )
plan1:upec.AssistancePlan(this!=null )
then
plan1.setDescription("cognitive stimulation and workshops memories");
end

rule"assistance plan 3"
ruleflow-group"NeurologyService2"
salience 2
when
syp1:upec.Symptom(description=="Apraxia" )
plan1:upec.AssistancePlan(this!=null )
then
plan1.setDescription("Physical exercises, physiotherapy");
end

rule"assistance plan 4"
ruleflow-group"NeurologyService2"
salience 4
when
npi:upec.NeuropsychologicalParameter(name=="NPI" && value<16)											
plan1:upec.AssistancePlan(this!=null )
then
plan1.setDescription("Psychiatric treatment");
end
