package upec.alzproject;
import upec.PatientRecord;
import upec.Symptom;
import upec.MedicalExamination;

rule"inserting patient symptoms into the wm"
ruleflow-group"TreatingPhysicianRules1"
salience 4
no-loop true
when
patient:upec.PatientRecord( syl:symptoms)
sy:upec.Symptom( )from syl
then
insertLogical(sy);
System.out.println("insert fact:"+ sy.getDescription());
end

rule"Suggested tests for the treating physician"
ruleflow-group"TreatingPhysicianRules1"
salience 4
no-loop true
when
(sym1:upec.Symptom( description=="Cognitive impairment") or sym2:upec.Symptom(description=="Psychomental change"))
examination1: upec.MedicalExamination(this!=null)
examination2:upec.MedicalExamination(this!=null)
then
examination1.setName("MMSE evaluation");
System.out.println("hehe!!!!");
examination2.setName("IADL evaluation");
end


