package upec.alzproject;
import upec.PatientRecord;
import upec.Symptom;
import upec.MedicalExamination;
import upec.NeuropsychologicalParameter;
import upec.Assignement;

rule"inserting patient symptoms into the wm"
ruleflow-group"TreatingPhysicianRules1"
salience 4
no-loop true
when
patient:upec.PatientRecord( syl:symptoms)
sy:upec.Symptom( )from syl
then
insertLogical(sy);
System.out.println("insert fact:"+ sy.getDescription());
end

rule"Suggested tests for the treating physician"
ruleflow-group"TreatingPhysicianRules1"
salience 4
no-loop true
when
sym1:upec.Symptom( description=="Cognitive impairment") 
examination1: upec.MedicalExamination(this!=null)
examination2:upec.MedicalExamination(this!=null)
then
examination1.setName("MMSE evaluation");
System.out.println("hehe!!!!");
examination2.setName("IADL evaluation");
end

rule"Suggested triage for the patient"
ruleflow-group"TreatingPhysicianRules1"
salience 4
no-loop true
when
mmse1:upec.NeuropsychologicalParameter(name=="MMSE evaluation" && value<24 )
iadl:upec.NeuropsychologicalParameter(name=="IADL evaluation" && value<8 )
triage1:upec.Assignement(this!=null )
then
triage1.setService("Alzheimer suspicion -> Neurology service");
end

rule"Suggested triage for the patient 1"
ruleflow-group"TreatingPhysicianRules1"
salience 4
no-loop true
when
mmse1:upec.NeuropsychologicalParameter(name=="MMSE evaluation" && value>=24 )
iadl:upec.NeuropsychologicalParameter(name=="IADL evaluation" && value==8 )
triage1:upec.Assignement(this!=null )
then
triage1.setService("No dementia is suspected");
end
