package upec;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Patient record")
public class PatientRecord implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Assignements")
    @org.kie.api.definition.type.Position(value = 8)
    private java.util.List<upec.Assignement> assignements;

    @org.kie.api.definition.type.Label(value = "Assistance plans")
    @org.kie.api.definition.type.Position(value = 10)
    private java.util.List<upec.AssistancePlan> assistancePlans;

    @org.kie.api.definition.type.Label(value = "Birth date")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date birthDate;

    @org.kie.api.definition.type.Label(value = "Diagnoses")
    @org.kie.api.definition.type.Position(value = 9)
    private java.util.List<upec.Diagnosis> diagnoses;

    @org.kie.api.definition.type.Label(value = "First name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String firstName;

    @org.kie.api.definition.type.Label(value = "Last name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String lastName;

    @org.kie.api.definition.type.Label(value = "Medical examinations")
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.List<upec.MedicalExamination> medicalExaminations;

    @org.kie.api.definition.type.Label(value = "Neuropsychological parameters")
    @org.kie.api.definition.type.Position(value = 6)
    private java.util.List<upec.NeuropsychologicalParameter> neuropsychologicalParameters;

    @org.kie.api.definition.type.Label(value = "Symptoms")
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.List<upec.Symptom> symptoms;

    @org.kie.api.definition.type.Label(value = "Treatments")
    @org.kie.api.definition.type.Position(value = 7)
    private java.util.List<upec.Treatment> treatments;

    @org.kie.api.definition.type.Label(value = "Vital signs")
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.List<upec.VitalSign> vitalSigns;

    public PatientRecord() {
    }
    
    public PatientRecord(java.lang.String firstName, java.lang.String lastName, java.util.Date birthDate, java.util.List<upec.Symptom> symptoms, java.util.List<upec.MedicalExamination> medicalExaminations, java.util.List<upec.VitalSign> vitalSigns, java.util.List<upec.NeuropsychologicalParameter> neuropsychologicalParameters, java.util.List<upec.Treatment> treatments, java.util.List<upec.Assignement> assignements, java.util.List<upec.Diagnosis> diagnoses, java.util.List<upec.AssistancePlan> assistancePlans) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.symptoms = symptoms;
        this.medicalExaminations = medicalExaminations;
        this.vitalSigns = vitalSigns;
        this.neuropsychologicalParameters = neuropsychologicalParameters;
        this.treatments = treatments;
        this.assignements = assignements;
        this.diagnoses = diagnoses;
        this.assistancePlans = assistancePlans;
    }

    public java.util.List<upec.Assignement> getAssignements() {
        return this.assignements;
    }
    
    public void setAssignements(java.util.List<upec.Assignement> assignements) {
        this.assignements = assignements;
    }

    public java.util.List<upec.AssistancePlan> getAssistancePlans() {
        return this.assistancePlans;
    }
    
    public void setAssistancePlans(java.util.List<upec.AssistancePlan> assistancePlans) {
        this.assistancePlans = assistancePlans;
    }

    public java.util.Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(java.util.Date birthDate) {
        this.birthDate = birthDate;
    }

    public java.util.List<upec.Diagnosis> getDiagnoses() {
        return this.diagnoses;
    }
    
    public void setDiagnoses(java.util.List<upec.Diagnosis> diagnoses) {
        this.diagnoses = diagnoses;
    }

    public java.lang.String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }

    public java.lang.String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }

    public java.util.List<upec.MedicalExamination> getMedicalExaminations() {
        return this.medicalExaminations;
    }
    
    public void setMedicalExaminations(java.util.List<upec.MedicalExamination> medicalExaminations) {
        this.medicalExaminations = medicalExaminations;
    }

    public java.util.List<upec.NeuropsychologicalParameter> getNeuropsychologicalParameters() {
        return this.neuropsychologicalParameters;
    }
    
    public void setNeuropsychologicalParameters(java.util.List<upec.NeuropsychologicalParameter> neuropsychologicalParameters) {
        this.neuropsychologicalParameters = neuropsychologicalParameters;
    }

    public java.util.List<upec.Symptom> getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(java.util.List<upec.Symptom> symptoms) {
        this.symptoms = symptoms;
    }

    public java.util.List<upec.Treatment> getTreatments() {
        return this.treatments;
    }
    
    public void setTreatments(java.util.List<upec.Treatment> treatments) {
        this.treatments = treatments;
    }

    public java.util.List<upec.VitalSign> getVitalSigns() {
        return this.vitalSigns;
    }
    
    public void setVitalSigns(java.util.List<upec.VitalSign> vitalSigns) {
        this.vitalSigns = vitalSigns;
    }

}